#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env.tunnel"

green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
red() { printf '\033[31m%s\033[0m\n' "$*"; }
die() { red "ERROR: $*"; exit 1; }

install_tailscale_if_needed() {
  if command -v tailscale >/dev/null 2>&1; then
    green "Tailscale is already installed."
    return
  fi

  yellow "Installing Tailscale using the official Linux install script..."
  curl -fsSL https://tailscale.com/install.sh | sh
}

start_tailscale() {
  if command -v systemctl >/dev/null 2>&1; then
    sudo systemctl enable --now tailscaled || true
  fi

  if ! pgrep -x tailscaled >/dev/null 2>&1; then
    yellow "Starting tailscaled manually for this WSL session..."
    sudo tailscaled --state=/var/lib/tailscale/tailscaled.state >/tmp/tailscaled.log 2>&1 &
    sleep 2
  fi
}

connect_tailscale() {
  if tailscale status >/dev/null 2>&1; then
    green "Tailscale is already connected."
  else
    yellow "Authenticating Tailscale. Follow the login URL if prompted."
    sudo tailscale up
  fi
}

write_env() {
  local tailscale_ip="$1"
  local api_port="${LOCAL_API_PORT:-3000}"
  local admin_port="${LOCAL_ADMIN_PORT:-3001}"
  local studio_port="${LOCAL_STUDIO_PORT:-3002}"

  if [[ -f "$ROOT_DIR/cloudflare.config.sh" ]]; then
    # shellcheck disable=SC1091
    source "$ROOT_DIR/cloudflare.config.sh"
    api_port="$LOCAL_API_PORT"
    admin_port="$LOCAL_ADMIN_PORT"
    studio_port="$LOCAL_STUDIO_PORT"
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by tailscale-setup.sh
TUNNEL_METHOD="tailscale"
TAILSCALE_IP="$tailscale_ip"
API_URL="http://$tailscale_ip:$api_port"
ADMIN_URL="http://$tailscale_ip:$admin_port"
STUDIO_URL="http://$tailscale_ip:$studio_port"
EOF
}

main() {
  install_tailscale_if_needed
  start_tailscale
  connect_tailscale

  local tailscale_ip
  tailscale_ip="$(tailscale ip -4 | head -n 1)"
  [[ -n "$tailscale_ip" ]] || die "Could not detect Tailscale IPv4 address."

  write_env "$tailscale_ip"
  green "Tailscale is ready."
  printf 'Stable Tailscale IP: %s\n' "$tailscale_ip"
  printf 'API URL: http://%s:%s\n' "$tailscale_ip" "${LOCAL_API_PORT:-3000}"
}

main "$@"
