#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$ROOT_DIR/cloudflare.config.sh"
ENV_FILE="$ROOT_DIR/.env.tunnel"
LOCAL_ENV_FILE="$ROOT_DIR/.env.local"
STATUS_FILE="$ROOT_DIR/.tunnel-status"
PID_FILE="$ROOT_DIR/.cloudflared-tunnel.pid"
LOG_FILE="$ROOT_DIR/.cloudflared-tunnel.log"

red() { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
die() { red "ERROR: $*"; exit 1; }

load_config() {
  [[ -f "$CONFIG_FILE" ]] || die "Missing $CONFIG_FILE. Fill it in or run ./cloudflare-setup.sh first."
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
  # shellcheck disable=SC1090
  [[ -f "$ENV_FILE" ]] && source "$ENV_FILE"
  # shellcheck disable=SC1090
  [[ -f "$LOCAL_ENV_FILE" ]] && source "$LOCAL_ENV_FILE"
  TUNNEL_CONFIG_FILE="$HOME/.cloudflared/$CF_TUNNEL_NAME.yml"
}

write_tunnel_env() {
  local method="$1"
  local api_url="$2"
  local admin_url="$3"
  local studio_url="$4"

  cat > "$ENV_FILE" <<EOF
# Generated by tunnel.sh / cloudflare-setup.sh
TUNNEL_METHOD="$method"
CF_TUNNEL_NAME="$CF_TUNNEL_NAME"
CF_DOMAIN="$CF_DOMAIN"
API_URL="$api_url"
ADMIN_URL="$admin_url"
STUDIO_URL="$studio_url"
EOF
}

write_status() {
  local status="$1"
  local method="$2"
  local api_url="$3"

  cat > "$STATUS_FILE" <<EOF
STATUS="$status"
METHOD="$method"
UPDATED_AT="$(date -Is)"
API_URL="$api_url"
EOF
}

find_tunnel_id() {
  cloudflared tunnel list --name "$CF_TUNNEL_NAME" --output json 2>/dev/null \
    | python3 -c 'import json,sys; data=json.load(sys.stdin); print(data[0]["id"] if data else "")' 2>/dev/null || true
}

is_cloudflare_running() {
  [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" >/dev/null 2>&1
}

stop_cloudflare() {
  if is_cloudflare_running; then
    kill "$(cat "$PID_FILE")"
    green "Stopped Cloudflare tunnel."
  else
    yellow "Cloudflare tunnel is not running."
  fi
  rm -f "$PID_FILE"
  write_status "stopped" "cloudflare" "${API_URL:-}"
}

start_cloudflare() {
  command -v cloudflared >/dev/null 2>&1 || die "cloudflared is not installed. Run ./cloudflare-setup.sh first."

  if [[ ! -f "$HOME/.cloudflared/cert.pem" ]]; then
    yellow "Cloudflare authentication is required. Follow the browser prompt."
    cloudflared tunnel login
  fi

  if [[ ! -f "$TUNNEL_CONFIG_FILE" ]] || [[ -z "$(find_tunnel_id)" ]]; then
    yellow "Named tunnel is not fully configured yet. Running one-time Cloudflare setup..."
    "$ROOT_DIR/cloudflare-setup.sh"
  fi

  local tunnel_id credentials_file
  tunnel_id="$(find_tunnel_id)"
  [[ -n "$tunnel_id" ]] || die "Tunnel $CF_TUNNEL_NAME does not exist. Run ./cloudflare-setup.sh first."
  credentials_file="$HOME/.cloudflared/$tunnel_id.json"
  [[ -f "$credentials_file" ]] || die "Missing credentials $credentials_file. Run ./cloudflare-setup.sh first."

  if is_cloudflare_running; then
    yellow "Cloudflare tunnel is already running with PID $(cat "$PID_FILE")."
  else
    yellow "Starting persistent Cloudflare tunnel: $CF_TUNNEL_NAME"
    nohup cloudflared tunnel --config "$TUNNEL_CONFIG_FILE" run "$CF_TUNNEL_NAME" > "$LOG_FILE" 2>&1 &
    echo "$!" > "$PID_FILE"
  fi

  local api_url="https://$CF_API_SUBDOMAIN.$CF_DOMAIN"
  local admin_url="https://$CF_ADMIN_SUBDOMAIN.$CF_DOMAIN"
  local studio_url="https://$CF_STUDIO_SUBDOMAIN.$CF_DOMAIN"

  write_tunnel_env "cloudflare" "$api_url" "$admin_url" "$studio_url"
  sleep 5

  if curl -fsS --max-time 10 "$api_url" >/dev/null; then
    write_status "running" "cloudflare" "$api_url"
    green "Cloudflare tunnel is active."
  else
    write_status "unreachable" "cloudflare" "$api_url"
    yellow "Tunnel started, but API is not reachable yet. Start your API on port $LOCAL_API_PORT and re-run ./tunnel-status.sh."
  fi

  printf 'API:    %s\n' "$api_url"
  printf 'Admin:  %s\n' "$admin_url"
  printf 'Studio: %s\n' "$studio_url"
}

get_public_ip() {
  curl -fsS --max-time 10 https://ifconfig.me || curl -fsS --max-time 10 https://api.ipify.org
}

use_direct_ip() {
  local public_ip
  public_ip="$(get_public_ip)" || die "Could not detect public IP."

  local api_url="http://$public_ip:$LOCAL_API_PORT"
  local admin_url="http://$public_ip:$LOCAL_ADMIN_PORT"
  local studio_url="http://$public_ip:$LOCAL_STUDIO_PORT"

  write_tunnel_env "direct-ip" "$api_url" "$admin_url" "$studio_url"
  write_status "manual-port-forward-required" "direct-ip" "$api_url"

  green "Direct public IP mode selected."
  printf 'Public IP: %s\n' "$public_ip"
  printf 'API:       %s\n' "$api_url"
  printf 'Admin:     %s\n' "$admin_url"
  printf 'Studio:    %s\n' "$studio_url"
  yellow "Open/forward ports $LOCAL_API_PORT, $LOCAL_ADMIN_PORT, and $LOCAL_STUDIO_PORT in your router and Windows Firewall."
}

choose_mode() {
  printf '\nChoose tunnel mode:\n'
  printf '  1) Cloudflare Tunnel - stable public URLs, no port forwarding\n'
  printf '  2) Direct public IP - requires router/firewall port forwarding\n'
  printf 'Selection [1]: '
  read -r selection
  case "${selection:-1}" in
    1) start_cloudflare ;;
    2) use_direct_ip ;;
    *) die "Invalid selection: $selection" ;;
  esac
}

main() {
  load_config
  case "${1:-}" in
    cloudflare) start_cloudflare ;;
    direct-ip) use_direct_ip ;;
    stop) stop_cloudflare ;;
    restart) stop_cloudflare; start_cloudflare ;;
    ""|start) choose_mode ;;
    *) die "Usage: ./tunnel.sh [start|cloudflare|direct-ip|stop|restart]" ;;
  esac
}

main "$@"
